/*
 * This file was automatically generated by EvoSuite
 * Fri Feb 20 00:27:36 GMT 2026
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ContaBancaria_ESTest extends ContaBancaria_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("m\"frYF", 2515.49130718657);
      String string0 = contaBancaria0.toString();
      assertEquals("Conta de m\"frYF - Saldo: R$ 2515.49 - Ativa", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria(";M+ C.e7k/iH-%G*J", 1.0);
      contaBancaria0.sacar(1.0);
      contaBancaria0.desativar();
      contaBancaria0.toString();
      assertFalse(contaBancaria0.isAtiva());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("", 740.1);
      ContaBancaria contaBancaria1 = new ContaBancaria("", 740.1);
      contaBancaria0.transferir(740.1, contaBancaria1);
      assertEquals(0.0, contaBancaria0.getSaldo(), 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("m\"frYF", 2515.49130718657);
      ContaBancaria contaBancaria1 = new ContaBancaria("m\"frYF", 0.0);
      contaBancaria1.desativar();
      // Undeclared exception!
      try { 
        contaBancaria0.transferir(3374.475929190591, contaBancaria1);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Conta destino inativa
         //
         verifyException("ContaBancaria", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("Conta inativa", 0.0);
      // Undeclared exception!
      try { 
        contaBancaria0.transferir(0.0, (ContaBancaria) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Conta destino n\u00C3\u00A3o pode ser nula
         //
         verifyException("ContaBancaria", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("-0#DZy", 0.0);
      // Undeclared exception!
      try { 
        contaBancaria0.sacar(1.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Saldo insuficiente
         //
         verifyException("ContaBancaria", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("", 0.0);
      // Undeclared exception!
      try { 
        contaBancaria0.sacar(0.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Valor do saque deve ser positivo
         //
         verifyException("ContaBancaria", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("-0#D%Zy", 0.0);
      contaBancaria0.desativar();
      // Undeclared exception!
      try { 
        contaBancaria0.sacar((-916.061045108164));
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Conta inativa
         //
         verifyException("ContaBancaria", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("", 0.0);
      // Undeclared exception!
      try { 
        contaBancaria0.depositar(0.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Valor do dep\u00C3\u00B3sito deve ser positivo
         //
         verifyException("ContaBancaria", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria(";M+ C.e7k/iH-%G*J", 1.0);
      contaBancaria0.sacar(1.0);
      contaBancaria0.desativar();
      // Undeclared exception!
      try { 
        contaBancaria0.depositar(1.0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Conta inativa
         //
         verifyException("ContaBancaria", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("f$=D85rpq=STAS_p", 1.0);
      // Undeclared exception!
      try { 
        contaBancaria0.desativar();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // N\u00C3\u00A3o \u00C3\u00A9 poss\u00C3\u00ADvel desativar conta com saldo positivo
         //
         verifyException("ContaBancaria", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("f$=D85rpq=STAS_p", 1.0);
      contaBancaria0.sacar(1.0);
      contaBancaria0.desativar();
      // Undeclared exception!
      try { 
        contaBancaria0.transferir((-1687.1), contaBancaria0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Conta origem inativa
         //
         verifyException("ContaBancaria", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("", 740.1);
      // Undeclared exception!
      try { 
        contaBancaria0.setTitular("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Titular inv\u00C3\u00A1lido
         //
         verifyException("ContaBancaria", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("", 740.1);
      contaBancaria0.setTitular("-y&MuCiCS$8");
      assertTrue(contaBancaria0.isAtiva());
      assertEquals(740.1, contaBancaria0.getSaldo(), 0.01);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("Conta inativa", 3374.475929190591);
      // Undeclared exception!
      try { 
        contaBancaria0.setTitular((String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Titular inv\u00C3\u00A1lido
         //
         verifyException("ContaBancaria", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ContaBancaria contaBancaria0 = null;
      try {
        contaBancaria0 = new ContaBancaria("&3Z*,7+<W", (-1.0));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Saldo inicial n\u00C3\u00A3o pode ser negativo
         //
         verifyException("ContaBancaria", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ContaBancaria contaBancaria0 = null;
      try {
        contaBancaria0 = new ContaBancaria("", 627.106823426427);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Titular inv\u00C3\u00A1lido
         //
         verifyException("ContaBancaria", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ContaBancaria contaBancaria0 = null;
      try {
        contaBancaria0 = new ContaBancaria((String) null, 0.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Titular inv\u00C3\u00A1lido
         //
         verifyException("ContaBancaria", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("$!rO@nNjvFp.D+F=.8t", 3197.98);
      contaBancaria0.getTitular();
      assertTrue(contaBancaria0.isAtiva());
      assertEquals(3197.98, contaBancaria0.getSaldo(), 0.01);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("$!rO@nNjvFp.D+F=.8t", 3197.98);
      double double0 = contaBancaria0.getSaldo();
      assertTrue(contaBancaria0.isAtiva());
      assertEquals(3197.98, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("\"+o>ckkg6&78S:~!S", 1.0);
      contaBancaria0.ativar();
      assertTrue(contaBancaria0.isAtiva());
      assertEquals(1.0, contaBancaria0.getSaldo(), 0.01);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("", 740.1);
      // Undeclared exception!
      try { 
        contaBancaria0.transferir(740.1, contaBancaria0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00C3\u00A3o \u00C3\u00A9 poss\u00C3\u00ADvel transferir para a mesma conta
         //
         verifyException("ContaBancaria", e);
      }
  }
}
